-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME,    
    SUM(o.AMOUNT * p.PRICE) as 'TOTAL_SALES'
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
    ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE "2022-05%"
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID