WITH sub as (
    SELECT d.ID, GROUP_CONCAT(CATEGORY) AS CATEGORY, FIRST_NAME, LAST_NAME, EMAIL
    FROM DEVELOPERS d
    JOIN SKILLCODES s
        ON d.SKILL_CODE & s.CODE = s.CODE
    GROUP BY ID, FIRST_NAME, LAST_NAME, EMAIL
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM sub
WHERE CATEGORY LIKE "%Front End%"